### ISSUE TITLE
Interface is used, but argument isn't type declared

### ISSUE THREAD

**Issue by Kilgaloon** [opulencephp/Opulence#104]
https://github.com/opulencephp/Opulence/blob/41fa106f87b42889d0849fc23558c952bca5fc07/src/Opulence/Authentication/Users/Orm/IUserRepository.php#L25

All `$user` arguments should be type declared to interface used.

**Comment by opulencephp** [comment]
The reason I did this was to interface more easily with `Opulence\Orm\Repositories\IRepository`.    In a perfect world, PHP would have generics, and I could strong type the repository args/return types, eg:

```php
interface IRepository<T>
{
    public function add(T $entity) : void;

    public function getById($id) : T;

    // etc...
}
```
However, since it doesn't, this is essentially what I'm forced to do to make it easier to utilize the ORM for `IUserRepository`.

**Comment by Kilgaloon** [comment]
Got the idea, just was a little bit confused when i saw `IUser` was used but nowhere type declared, except it is declared in docblock.

**Comment by opulencephp** [comment]
I'm going to go ahead and close this if you don't mind.
