### ISSUE TITLE
Failed opening required '/autoload.php'

### ISSUE THREAD

**Issue by leelu** [opulencephp/Opulence#24]
Hi,

After installing opulence using composer as mentioned in doc. I tried to rename the app name using command given in doc as below

php apex app:rename Project NEW_NAME

Below is the error i am getting :

`[leela@ip-centosami project]$ ls`
`apex  bootstrap  composer.json  config  phpunit.xml  public  resources  src  tests  tmp`
`[leela@ip-centosami project]$ php apex app:rename project genius`
`PHP Warning:  require(/autoload.php): failed to open stream: No such file or directory in /var/www/app1/project/config/paths.php on line 123
PHP Fatal error:  require(): Failed opening required '/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/app1/project/config/paths.php on line 123`
`[leela@ip-centosami project]$`

Am I missing anything in installation of the project ?

**Comment by jdrab** [comment]
Hi, @leelu I installed opulence 30 minutes ago using `composer create-project opulence/project --prefer-dist`.
I renamed it using `php apex app:rename..` but I don't have that require statement on line 123. 
Did you modify config/paths.php?

**Comment by opulencephp** [comment]
Hi @leelu.  I wasn't able to reproduce that issue.  When did you install Opulence?  There have been some breaking changes up until the release candidate last night.  If you know what version you were upgrading from, you could look at the [upgrade guide](https://www.opulencephp.com/docs/1.0/upgrading).  Otherwise, you could reference the latest [skeleton project](https://github.com/opulencephp/Project) to see what differences your config/paths.php has.

**Comment by leelu** [comment]
Hi jdrab and opulencephp

Sorry my bad, extension mbstring & mcrypt were missing in my PHP7 installation which caused the issue. It's working now :). 

Regards
Leelu

**Comment by opulencephp** [comment]
Haha don't worry about it.  Glad to hear you got it sorted!

Dave
