### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by namaless** [opulencephp/Opulence#26]
Hello, I checked the maintenance mode and it's normal the view not change? I see only the page title get "Error" and nothing more.

I installed clean project and nothing change, only run `php apex app:down` command.

Thanks.

**Comment by namaless** [comment]
Ok I found the problem, is in the view:

`resources/views/errors/html/Error.fortune.php`

```
<% part("content") %>
<h2><% show("errorTitle") %></h2>
<% part("errorMessage") %>
Something went wrong.  We will look into what happened.
<% show %>
<% endpart %>
```

But in the home nothing part are defined so nothing in the page change.

Ill send a PR for this.

**Comment by opulencephp** [comment]
Thanks for the report. I'll check it out as soon I get back to my office. 
-------- Original message --------From: Pereira Ricardo <notifications@github.com> Date: 10/29/16  12:15 PM  (GMT-06:00) To: opulencephp/Opulence <Opulence@noreply.github.com> Subject: [opulencephp/Opulence] Maintenance mode (#26) 
Hello, I checked the maintenance mode and it's normal the view not change? I see only the page title get "Error" and nothing more.

I installed clean project and nothing change, only run php apex app:down command.

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opulencephp/Opulence","title":"opulencephp/Opulence","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opulencephp/Opulence"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Maintenance mode (#26)"}],"action":{"name":"View Issue","url":"https://github.com/opulencephp/Opulence/issues/26"}}}

**Comment by namaless** [comment]
Clear your message because you posted some informations about your api's 🗡

**Comment by opulencephp** [comment]
Weird. I replied via email, and it appended all that stuff. Thanks for the heads up.

**Comment by opulencephp** [comment]
OK, I've fixed this issue.  It was due to a change I made when trying to simplify the views.  I accidentally removed the "Master" view template, which was the source of all these issues.
