### ISSUE TITLE
Suggestion: Add option to clear console cache for apex

### ISSUE THREAD

**Issue by exts** [opulencephp/Opulence#30]
One thing I learned is that there's a cache file for console that almost instantly gets cached in `tmp/framework/console` called `cachedBootstrapperRegistry.json` and say if you remove a bootstrap class it'll throw a fatal error making apex compeltely unusable because it's looking for a class that doesn't exist anymore.

My suggestion is to be able to call: `php apex --hard-cache-clear` which does one thing and that's to clear the cache directly and nothing else that way you won't have to manually do it to get apex working again.

I'm still learning Opulence, so maybe I'll try creating a PR if I figure it out tonight.

**Comment by opulencephp** [comment]
That's a good suggestion.  The tricky part is executing this command before the bootstrappers start.  The way the [skeleton project](https://github.com/opulencephp/Project) is written, the bootstrappers are always run prior to the command being executed.  I don't want to just put all this special logic inside the skeleton project, because then it becomes harder for everyone to maintain (as opposed to it being part of the Opulence framework).  I'll have to think about the best way to solve this.

**Comment by exts** [comment]
Maybe instead of updating apex, create a new console application specifically for dealing with the cache? eg.: `php apex-cache console:clear` `php apex-cache view:rebuild`

**Comment by opulencephp** [comment]
To keep it clean, I'd prefer to keep it as a command in `php apex` if at all possible.

**Comment by opulencephp** [comment]
I believe I worked out a fix for this last night.  Expect it to be released in the next day or two.

**Comment by opulencephp** [comment]
I've added the ability to intelligently blow away the cached bootstrapper registry if the bootstrappers are updated.  Please look at the [upgrade guide](https://www.opulencephp.com/docs/1.0/upgrading#1.0.0-rc3) for the small change to make to your project to take advantage of this feature.

Thanks for bringing this to my attention!

**Comment by exts** [comment]
No problem.
